// <auto-generated />
using System;
using Data_Access_Layer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Access_Layer.Migrations
{
    [DbContext(typeof(MaskinContext))]
    [Migration("20260429102330_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data_Access_Layer.Models.AfsluttetService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaskineId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceOpgaveId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("UdførtDato")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MaskineId");

                    b.HasIndex("ServiceOpgaveId");

                    b.ToTable("AfsluttedeServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaskineId = 1,
                            Note = "Service afsluttet uden anmærkninger",
                            ServiceOpgaveId = 1,
                            UdførtDato = new DateOnly(2025, 10, 1)
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Models.EftersynsRegel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Regel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EftersynsRegler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Regel = "Tjek bremser for slid"
                        },
                        new
                        {
                            Id = 2,
                            Regel = "Tjek nødstop funktion"
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Models.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CvrNummer")
                        .HasColumnType("int");

                    b.Property<bool>("ErAktiv")
                        .HasColumnType("bit");

                    b.Property<string>("FirmaNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktPersonNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktPersonTelefonnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAdresse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kunder");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "Testvej 1",
                            CvrNummer = 11223344,
                            ErAktiv = true,
                            FirmaNavn = "Byg & Maskin A/S",
                            KontaktPersonNavn = "Jens Jensen",
                            KontaktPersonTelefonnummer = "12341234",
                            MailAdresse = "B&M@test.com"
                        },
                        new
                        {
                            Id = 2,
                            Adresse = "Testvej 2",
                            CvrNummer = 99887766,
                            ErAktiv = true,
                            FirmaNavn = "Skovens Entreprenør",
                            KontaktPersonNavn = "Mia Skov",
                            KontaktPersonTelefonnummer = "43214321",
                            MailAdresse = "Skovens@test.com"
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Models.Maskine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KundeId")
                        .HasColumnType("int");

                    b.Property<int>("MaskineType")
                        .HasColumnType("int");

                    b.Property<string>("Producent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerieNummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.ToTable("Maskiner");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KundeId = 1,
                            MaskineType = 0,
                            Producent = "Volvo",
                            SerieNummer = "SN-1001"
                        },
                        new
                        {
                            Id = 2,
                            KundeId = 2,
                            MaskineType = 2,
                            Producent = "CAT",
                            SerieNummer = "SN-2002"
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Models.MaterialeLinje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaterialeListeId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialeTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("MatrialeTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialeListeId");

                    b.HasIndex("MaterialeTypeId");

                    b.ToTable("MaterialeLinjer");
                });

            modelBuilder.Entity("Data_Access_Layer.Models.MaterialeListe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("MaterialeLister");
                });

            modelBuilder.Entity("Data_Access_Layer.Models.MaterialeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaterialeBeskrivelse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialeType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaterialeBeskrivelse = "Motorolie 5W-30"
                        },
                        new
                        {
                            Id = 2,
                            MaterialeBeskrivelse = "Hydraulikslange 2m"
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Models.Medarbejder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AktivSessionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeOrdHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAdresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedarbejderNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medarbejdere");

                    b.HasData(
                        new
                        {
                            Id = "M1",
                            MailAdresse = "admin@ipmaskin.dk",
                            MedarbejderNavn = "Admin Alice"
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Models.OpgaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OpgaveBeskrivelse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OpgaveTyper");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OpgaveBeskrivelse = "Olieskift"
                        },
                        new
                        {
                            Id = 2,
                            OpgaveBeskrivelse = "Udskiftning af hydraulikslange"
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Models.Påmindelse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("PåmindelsesDato")
                        .HasColumnType("date");

                    b.Property<int?>("ServiceOpgaveId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOpgaveId");

                    b.ToTable("Påmindelser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PåmindelsesDato = new DateOnly(2026, 9, 1),
                            ServiceOpgaveId = 1
                        },
                        new
                        {
                            Id = 2,
                            PåmindelsesDato = new DateOnly(2026, 10, 1),
                            ServiceOpgaveId = 2
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Models.ServiceOpgave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date");

                    b.Property<int?>("MaskineId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialeListeId")
                        .HasColumnType("int");

                    b.Property<string>("MedarbejderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceInterval")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceTeknikkerId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("SidstUdførtDato")
                        .HasColumnType("date");

                    b.Property<string>("SidstUdførtNote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaskineId");

                    b.HasIndex("MaterialeListeId");

                    b.HasIndex("MedarbejderId");

                    b.HasIndex("ServiceTeknikkerId");

                    b.ToTable("ServiceOpgaver");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Data_Access_Layer.Models.ServiceTeknikker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TeknikkerNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTeknikkere");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TeknikkerNavn = "Tom Værktøj",
                            TelefonNummer = "11223344"
                        });
                });

            modelBuilder.Entity("EftersynsRegelSikkerhedsEftersyn", b =>
                {
                    b.Property<int>("EftersynsRegelListeId")
                        .HasColumnType("int");

                    b.Property<int>("SikkerhedsEftersynId")
                        .HasColumnType("int");

                    b.HasKey("EftersynsRegelListeId", "SikkerhedsEftersynId");

                    b.HasIndex("SikkerhedsEftersynId");

                    b.ToTable("EftersynsRegelLinks", (string)null);

                    b.HasData(
                        new
                        {
                            EftersynsRegelListeId = 1,
                            SikkerhedsEftersynId = 2
                        });
                });

            modelBuilder.Entity("OpgaveTypeService", b =>
                {
                    b.Property<int>("OpgaveTypeListeId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("OpgaveTypeListeId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceOpgaveTypeLinks", (string)null);

                    b.HasData(
                        new
                        {
                            OpgaveTypeListeId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            OpgaveTypeListeId = 2,
                            ServiceId = 1
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Models.Service", b =>
                {
                    b.HasBaseType("Data_Access_Layer.Models.ServiceOpgave");

                    b.Property<int?>("Servicetype")
                        .HasColumnType("int");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deadline = new DateOnly(2026, 10, 1),
                            MaskineId = 1,
                            MedarbejderId = "M1",
                            ServiceInterval = 2,
                            ServiceTeknikkerId = 1,
                            SidstUdførtDato = new DateOnly(2025, 10, 1),
                            SidstUdførtNote = "Olie skiftet, alt ok",
                            Servicetype = 0
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Models.SikkerhedsEftersyn", b =>
                {
                    b.HasBaseType("Data_Access_Layer.Models.ServiceOpgave");

                    b.ToTable("SikkerhedsEftersyn");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Deadline = new DateOnly(2026, 11, 1),
                            MaskineId = 2,
                            MedarbejderId = "M1",
                            ServiceInterval = 2,
                            ServiceTeknikkerId = 1,
                            SidstUdførtDato = new DateOnly(2025, 11, 1),
                            SidstUdførtNote = "Nødstop testet og godkendt"
                        });
                });

            modelBuilder.Entity("Data_Access_Layer.Models.AfsluttetService", b =>
                {
                    b.HasOne("Data_Access_Layer.Models.Maskine", null)
                        .WithMany("ServiceHistorikListe")
                        .HasForeignKey("MaskineId");

                    b.HasOne("Data_Access_Layer.Models.ServiceOpgave", "ServiceOpgave")
                        .WithMany()
                        .HasForeignKey("ServiceOpgaveId");

                    b.Navigation("ServiceOpgave");
                });

            modelBuilder.Entity("Data_Access_Layer.Models.Maskine", b =>
                {
                    b.HasOne("Data_Access_Layer.Models.Kunde", "Kunde")
                        .WithMany("MaskineListe")
                        .HasForeignKey("KundeId");

                    b.Navigation("Kunde");
                });

            modelBuilder.Entity("Data_Access_Layer.Models.MaterialeLinje", b =>
                {
                    b.HasOne("Data_Access_Layer.Models.MaterialeListe", null)
                        .WithMany("MaterialeLinjeListe")
                        .HasForeignKey("MaterialeListeId");

                    b.HasOne("Data_Access_Layer.Models.MaterialeType", "MaterialeType")
                        .WithMany()
                        .HasForeignKey("MaterialeTypeId");

                    b.Navigation("MaterialeType");
                });

            modelBuilder.Entity("Data_Access_Layer.Models.Påmindelse", b =>
                {
                    b.HasOne("Data_Access_Layer.Models.ServiceOpgave", "ServiceOpgave")
                        .WithMany("PåmindelseListe")
                        .HasForeignKey("ServiceOpgaveId");

                    b.Navigation("ServiceOpgave");
                });

            modelBuilder.Entity("Data_Access_Layer.Models.ServiceOpgave", b =>
                {
                    b.HasOne("Data_Access_Layer.Models.Maskine", "Maskine")
                        .WithMany("ServiceOgEftersynAftalerListe")
                        .HasForeignKey("MaskineId");

                    b.HasOne("Data_Access_Layer.Models.MaterialeListe", "MaterialeListe")
                        .WithMany()
                        .HasForeignKey("MaterialeListeId");

                    b.HasOne("Data_Access_Layer.Models.Medarbejder", "Medarbejder")
                        .WithMany()
                        .HasForeignKey("MedarbejderId");

                    b.HasOne("Data_Access_Layer.Models.ServiceTeknikker", "ServiceTeknikker")
                        .WithMany()
                        .HasForeignKey("ServiceTeknikkerId");

                    b.Navigation("Maskine");

                    b.Navigation("MaterialeListe");

                    b.Navigation("Medarbejder");

                    b.Navigation("ServiceTeknikker");
                });

            modelBuilder.Entity("EftersynsRegelSikkerhedsEftersyn", b =>
                {
                    b.HasOne("Data_Access_Layer.Models.EftersynsRegel", null)
                        .WithMany()
                        .HasForeignKey("EftersynsRegelListeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Access_Layer.Models.SikkerhedsEftersyn", null)
                        .WithMany()
                        .HasForeignKey("SikkerhedsEftersynId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpgaveTypeService", b =>
                {
                    b.HasOne("Data_Access_Layer.Models.OpgaveType", null)
                        .WithMany()
                        .HasForeignKey("OpgaveTypeListeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Data_Access_Layer.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data_Access_Layer.Models.Service", b =>
                {
                    b.HasOne("Data_Access_Layer.Models.ServiceOpgave", null)
                        .WithOne()
                        .HasForeignKey("Data_Access_Layer.Models.Service", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data_Access_Layer.Models.SikkerhedsEftersyn", b =>
                {
                    b.HasOne("Data_Access_Layer.Models.ServiceOpgave", null)
                        .WithOne()
                        .HasForeignKey("Data_Access_Layer.Models.SikkerhedsEftersyn", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data_Access_Layer.Models.Kunde", b =>
                {
                    b.Navigation("MaskineListe");
                });

            modelBuilder.Entity("Data_Access_Layer.Models.Maskine", b =>
                {
                    b.Navigation("ServiceHistorikListe");

                    b.Navigation("ServiceOgEftersynAftalerListe");
                });

            modelBuilder.Entity("Data_Access_Layer.Models.MaterialeListe", b =>
                {
                    b.Navigation("MaterialeLinjeListe");
                });

            modelBuilder.Entity("Data_Access_Layer.Models.ServiceOpgave", b =>
                {
                    b.Navigation("PåmindelseListe");
                });
#pragma warning restore 612, 618
        }
    }
}
