// <auto-generated />
using System;
using Data_Access_Layer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_Access_Layer.Migrations
{
    [DbContext(typeof(MaskinContext))]
    partial class MaskinContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Business_Logic_Layer.AfsluttetService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaskineId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceOpgaveId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("UdførtDato")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MaskineId");

                    b.HasIndex("ServiceOpgaveId");

                    b.ToTable("AfsluttedeServices");
                });

            modelBuilder.Entity("Business_Logic_Layer.EftersynsRegel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Regel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SikkerhedsEftersynId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SikkerhedsEftersynId");

                    b.ToTable("EftersynsRegler");
                });

            modelBuilder.Entity("Business_Logic_Layer.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CvrNummer")
                        .HasColumnType("int");

                    b.Property<bool>("ErAktiv")
                        .HasColumnType("bit");

                    b.Property<string>("FirmaNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktPersonNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktPersonTelefonnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAdresse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("Business_Logic_Layer.Maskine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KundeId")
                        .HasColumnType("int");

                    b.Property<int>("MaskineType")
                        .HasColumnType("int");

                    b.Property<string>("Producent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerieNummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.ToTable("Maskiner");
                });

            modelBuilder.Entity("Business_Logic_Layer.MaterialeLinje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<string>("Information")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaterialeListeId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialeTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("MatrialeTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaterialeListeId");

                    b.HasIndex("MaterialeTypeId");

                    b.ToTable("MaterialeLinjer");
                });

            modelBuilder.Entity("Business_Logic_Layer.MaterialeListe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("MaterialeLister");
                });

            modelBuilder.Entity("Business_Logic_Layer.MaterialeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaterialeBeskrivelse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaterialeTyper");
                });

            modelBuilder.Entity("Business_Logic_Layer.Medarbejder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KodeOrdHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAdresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedarbejderNavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medarbejdere");
                });

            modelBuilder.Entity("Business_Logic_Layer.OpgaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OpgaveBeskrivelse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("OpgaveTyper");
                });

            modelBuilder.Entity("Business_Logic_Layer.Påmindelse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("PåmindelsesDato")
                        .HasColumnType("date");

                    b.Property<int?>("ServiceOpgaveId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOpgaveId");

                    b.ToTable("Påmindelser");
                });

            modelBuilder.Entity("Business_Logic_Layer.ServiceOpgave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int?>("MaskineId")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialeListeId")
                        .HasColumnType("int");

                    b.Property<string>("MedarbejderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceInterval")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceTeknikkerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SidstUdførtDato")
                        .HasColumnType("date");

                    b.Property<string>("SidstUdførtNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialeListeId");

                    b.HasIndex("MedarbejderId");

                    b.HasIndex("ServiceTeknikkerId");

                    b.ToTable("ServiceOpgaver");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ServiceOpgave");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Business_Logic_Layer.ServiceTeknikker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TeknikkerNavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTeknikkere");
                });

            modelBuilder.Entity("Business_Logic_Layer.Service", b =>
                {
                    b.HasBaseType("Business_Logic_Layer.ServiceOpgave");

                    b.Property<int>("Servicetype")
                        .HasColumnType("int");

                    b.HasIndex("MaskineId");

                    b.HasDiscriminator().HasValue("Service");
                });

            modelBuilder.Entity("Business_Logic_Layer.SikkerhedsEftersyn", b =>
                {
                    b.HasBaseType("Business_Logic_Layer.ServiceOpgave");

                    b.HasIndex("MaskineId");

                    b.HasDiscriminator().HasValue("SikkerhedsEftersyn");
                });

            modelBuilder.Entity("Business_Logic_Layer.AfsluttetService", b =>
                {
                    b.HasOne("Business_Logic_Layer.Maskine", null)
                        .WithMany("ServiceHistorikListe")
                        .HasForeignKey("MaskineId");

                    b.HasOne("Business_Logic_Layer.ServiceOpgave", "ServiceOpgave")
                        .WithMany()
                        .HasForeignKey("ServiceOpgaveId");

                    b.Navigation("ServiceOpgave");
                });

            modelBuilder.Entity("Business_Logic_Layer.EftersynsRegel", b =>
                {
                    b.HasOne("Business_Logic_Layer.SikkerhedsEftersyn", null)
                        .WithMany("EftersynsRegelListe")
                        .HasForeignKey("SikkerhedsEftersynId");
                });

            modelBuilder.Entity("Business_Logic_Layer.Maskine", b =>
                {
                    b.HasOne("Business_Logic_Layer.Kunde", "Kunde")
                        .WithMany("MaskineListe")
                        .HasForeignKey("KundeId");

                    b.Navigation("Kunde");
                });

            modelBuilder.Entity("Business_Logic_Layer.MaterialeLinje", b =>
                {
                    b.HasOne("Business_Logic_Layer.MaterialeListe", null)
                        .WithMany("MaterialeLinjeListe")
                        .HasForeignKey("MaterialeListeId");

                    b.HasOne("Business_Logic_Layer.MaterialeType", "MaterialeType")
                        .WithMany()
                        .HasForeignKey("MaterialeTypeId");

                    b.Navigation("MaterialeType");
                });

            modelBuilder.Entity("Business_Logic_Layer.OpgaveType", b =>
                {
                    b.HasOne("Business_Logic_Layer.Service", null)
                        .WithMany("OpgaveTypeListe")
                        .HasForeignKey("ServiceId");
                });

            modelBuilder.Entity("Business_Logic_Layer.Påmindelse", b =>
                {
                    b.HasOne("Business_Logic_Layer.ServiceOpgave", "ServiceOpgave")
                        .WithMany("PåmindelseListe")
                        .HasForeignKey("ServiceOpgaveId");

                    b.Navigation("ServiceOpgave");
                });

            modelBuilder.Entity("Business_Logic_Layer.ServiceOpgave", b =>
                {
                    b.HasOne("Business_Logic_Layer.MaterialeListe", "MaterialeListe")
                        .WithMany()
                        .HasForeignKey("MaterialeListeId");

                    b.HasOne("Business_Logic_Layer.Medarbejder", "Medarbejder")
                        .WithMany()
                        .HasForeignKey("MedarbejderId");

                    b.HasOne("Business_Logic_Layer.ServiceTeknikker", "ServiceTeknikker")
                        .WithMany()
                        .HasForeignKey("ServiceTeknikkerId");

                    b.Navigation("MaterialeListe");

                    b.Navigation("Medarbejder");

                    b.Navigation("ServiceTeknikker");
                });

            modelBuilder.Entity("Business_Logic_Layer.Service", b =>
                {
                    b.HasOne("Business_Logic_Layer.Maskine", "Maskine")
                        .WithMany("ServiceListe")
                        .HasForeignKey("MaskineId");

                    b.Navigation("Maskine");
                });

            modelBuilder.Entity("Business_Logic_Layer.SikkerhedsEftersyn", b =>
                {
                    b.HasOne("Business_Logic_Layer.Maskine", "Maskine")
                        .WithMany("SikkerhedsEftersynListe")
                        .HasForeignKey("MaskineId");

                    b.Navigation("Maskine");
                });

            modelBuilder.Entity("Business_Logic_Layer.Kunde", b =>
                {
                    b.Navigation("MaskineListe");
                });

            modelBuilder.Entity("Business_Logic_Layer.Maskine", b =>
                {
                    b.Navigation("ServiceHistorikListe");

                    b.Navigation("ServiceListe");

                    b.Navigation("SikkerhedsEftersynListe");
                });

            modelBuilder.Entity("Business_Logic_Layer.MaterialeListe", b =>
                {
                    b.Navigation("MaterialeLinjeListe");
                });

            modelBuilder.Entity("Business_Logic_Layer.ServiceOpgave", b =>
                {
                    b.Navigation("PåmindelseListe");
                });

            modelBuilder.Entity("Business_Logic_Layer.Service", b =>
                {
                    b.Navigation("OpgaveTypeListe");
                });

            modelBuilder.Entity("Business_Logic_Layer.SikkerhedsEftersyn", b =>
                {
                    b.Navigation("EftersynsRegelListe");
                });
#pragma warning restore 612, 618
        }
    }
}
